version: "3.8"


services:

  server:
    build: ./crates/coffee-back
    ports:
      - "${BACK_PORT}:8081"
    command: [ "coffee-back" ]
    env_file:
      - .env
    depends_on:
      - db
    restart: always
#    networks:
#      - flops